version: "3.9"
services:
  frontend:
    build: 
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=${API_URL}
    container_name: mnemos-web
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=${API_URL}
    ports:
      - "49182:80"

  backend:
    build: ./backend
    container_name: mnemos-api
    ports:
      - "49183:8000"